### ISSUE TITLE
Public call to make slug from string

### ISSUE THREAD

**Issue by dreamingmind** [cwbit/cakephp-sluggable#1]
It would be super convenient to be able to make a call to the behavior to convert any provided string into a slug. Outside of the save cycle.

**Comment by dreamingmind** [comment]
Yeah. well never mind. the solution is obvious and I feel a bit foooooolish

**Comment by cwbit** [comment]
Hah! Actually you're right, tho. The slug function might need it's accessibility opened up a little bit. It could also be moved out into a Lib or Utility class that could be called/included separately as the task it's performing doesn't need to be coupled so tightly to a behaviour.

**Comment by dreamingmind** [comment]
Hey, sweet! I'll check it out. I've got just the place to fold it into my code.

**Comment by cwbit** [comment]
Nice! Let me know how it goes! Check out the test cases, too, for examples of how to use it - esp for the auto string-replacement

**Comment by dreamingmind** [comment]
Updated my app. Wrote in the new utility call. Works perfectly!

I used it in a couple of modes, with a string, with a replacement map and an entity. Everything I used was perfect.

Thanks

**Comment by cwbit** [comment]
Great! Thanks for the feedback and the idea to break this out
